// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcxsxzgyiijgczoldkty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjeHN4emd5aWlqZ2N6b2xka3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTc3NDIsImV4cCI6MjA3MTY3Mzc0Mn0.Fk2arDO-KH2Q7ZhYiRD9GSOTYsBHcTIHCM-paV4pb3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});